spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_library?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-request-size: 9MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    root: info
    com:
      ice: info
  file: online-library-server.log

library:
  ftp:
    host: 118.25.57.216
    port: 21
    username: uftp
    password: uftp
    basePath: /home/uftp/online-library
    previewPath: /home/uftp/online-library/preview/
  file:
    base-path: http://118.25.57.216:8090
    visit-path: http://118.25.57.216:8090/online-library/


permission:
  baseUrl: http://localhost:8080
